spring:
  application:
    name: gateway
server:
  port: 7771
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
          defaultZone: http://localhost:7770/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
