spring:
  application:
    name: reservation-service

server:
  port: 7772

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7770/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true